# Generated by Django 6.0.6 on 2026-07-07 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('active', 'Active'), ('finished', 'Finished')], default='draft', max_length=16)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_expeditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExpeditionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed')], default='invited', max_length=16)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='expeditions.expedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-invited_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='expedition',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='expedition_capacity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='expeditionmember',
            constraint=models.UniqueConstraint(fields=('expedition', 'user'), name='unique_expedition_member'),
        ),
    ]
